services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    container_name: supertokens
    hostname: supertokens
    restart: unless-stopped
    ports:
      - 3567:3567
    environment:
      - POSTGRESQL_CONNECTION_URI=postgresql://postgres:Password123@postgres:5432/postgres_db
      - API_KEYS=your-api-key-change-me