services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    user: root
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - local-setup-mssql:/var/opt/mssql/data

volumes:
  local-setup-mssql:
    driver: local