services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    # environment:
    # - NEO4J_AUTH=none
    hostname: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - local-setup-neo4j:/data

volumes:
  local-setup-neo4j:
    driver: local