version: "3"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    hostname: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./.qdrant:/qdrant/storage
    networks:
      - localhost-network

networks:
  localhost-network:
    external: true
    name: localhost-network