services:
  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense
    hostname: typesense
    restart: unless-stopped
    ports:
      - 8108:8108
    volumes:
      - local-setup-typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
  local-setup-typesense:
    driver: local