services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    hostname: seq
    restart: unless-stopped
    ports:
      - 5341:80
      - 5342:5341
    environment:
      - ACCEPT_EULA=Y