version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq
    networks:
      - localhost-network

networks:
  localhost-network:
    external: true
    name: localhost-network