version: "3"

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    hostname: seq
    restart: unless-stopped
    ports:
      - 5341:80
      - 5342:5341
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./.seq:/data
    networks:
      - localhost-network

networks:
  localhost-network:
    external: true
    name: localhost-network