services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - local-setup-rabbitmq:/var/lib/rabbitmq

volumes:
  local-setup-rabbitmq:
    driver: local