services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
#    environment:
#      - MODEL=llama2:7b
    hostname: ollama
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - local-setup-ollama:/root/.ollama

volumes:
  local-setup-ollama:
    driver: local