version: "3"

services:
  webhook:
    image: thecatlady/webhook
    container_name: webhook
    hostname: webhook
    command: -verbose -hooks=webhooks.json -hotreload
    volumes:
      - ${WEBHOOK_LOCATION}:/config:ro
    restart: always
    networks:
      - vps-network

networks:
  vps-network:
    external: true
    name: vps-network