version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - ./.mssql:/var/opt/mssql/data
    networks:
      - vps-network

networks:
  vps-network:
    external: true
    name: vps-network