version: "3"

services:
  proxy:
    image: mattes/rotating-proxy:latest
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    ports:
      - 5566:5566 
      - 4444:4444
    environment:
      - tors=25
    networks:
      - vps-network

networks:
  vps-network:
    external: true
    name: vps-network