version: "3"

services:
  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    hostname: ngrok
    restart: always
    ports:
      - 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: ["http", "rabbitmq:15672"]
    networks:
      - vps-network

networks:
  vps-network:
    external: true
    name: vps-network